import type { Metadata, Viewport } from "next";
import { Barlow_Condensed, Hanken_Grotesk, JetBrains_Mono } from "next/font/google";
import { Providers } from "@/components/Providers";
import { startupImages } from "@/lib/pwa/splash";
import { VIEWPORT_GAP_SCRIPT } from "@/lib/pwa/viewport-gap";
import { metadataBase, SITE_DESCRIPTION, SITE_NAME } from "@/lib/site";
import "./globals.css";

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-barlow-condensed",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: metadataBase(),
  title: { default: SITE_NAME, template: `%s · ${SITE_NAME}` },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  // Private app: keep it out of search indexes. Link-preview crawlers read the tags below regardless.
  robots: { index: false, follow: false },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en_US",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  twitter: { card: "summary_large_image", title: SITE_NAME, description: SITE_DESCRIPTION },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: SITE_NAME,
    // Launch screens for current iPhones (public/splash, generated by scripts/gen-splash.ts).
    startupImage: startupImages,
  },
  formatDetection: { telephone: false },
  // Next only emits mobile-web-app-capable; iOS Safari still keys off the apple- variant.
  other: { "apple-mobile-web-app-capable": "yes" },
  icons: {
    icon: [
      { url: "/icons/icon.svg", type: "image/svg+xml" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/icons/icon-180.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0A0B0D",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`dark ${hanken.variable} ${barlowCondensed.variable} ${jetbrainsMono.variable}`}
      // The head script below may set --vh-gap in <html>'s style attribute before hydration.
      suppressHydrationWarning
    >
      <head>
        {/* Before first paint: measure the iOS 26 standalone viewport shortfall (src/lib/pwa/viewport-gap.ts). */}
        <script dangerouslySetInnerHTML={{ __html: VIEWPORT_GAP_SCRIPT }} />
      </head>
      <body className="min-h-app antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
